name: Python Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        cache: "pip"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov pylint
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Pylint
      run: |
        pylint app/ operations/ tests/ --fail-under=8  # ✅ Enforces a minimum Pylint score of 8

    - name: Run Pytest with Coverage
      run: |
        pytest tests/ --cov=app --cov=operations --cov-report=term-missing --cov-fail-under=80  # ✅ Requires 80% test coverage